---
  - ansible.builtin.debug:
      msg: "Looking up {{ item.item_name }}.{{ item.field_name }} in {{ onepassword_vault }}"
    tags: op_secrets
    when: op_secrets_debug

  - name: Retrieving Secret
    onepassword.connect.field_info:
      item: "{{ item.item_name }}"
      field: "{{ item.field_name }}"
      vault: "{{ onepassword_vault }}"
    no_log: op_secrets_secure_logging
    register: op_secret_item
    delegate_to: "{{ op_secrets_delegate }}"
    tags: op_secrets

  - ansible.builtin.debug:
      msg: "Retrieved {{ op_secret_item.field.id }} from {{ item.item_name }}"
    tags: op_secrets
    when: op_secrets_debug

  - name: Set the value as a fact on the target host
    set_fact: "{{ item.fact_name }}={{ op_secret_item.field.value }}"
    tags: op_secrets

  - ansible.builtin.debug:
      msg: "Set a fact named {{ item.fact_name }} from {{ item.item_name }}"
    tags: op_secrets
    when: op_secrets_debug
